### ISSUE TITLE
search/cases fails to render

### ISSUE THREAD

**Issue by mattkiefer** [INN/cpd-settlements#6]
In testing, page fails to render case data, just "Loading".

Console output:
search-libs.min.js:9 Uncaught TypeError: this.$el.chosen is not a function
    at child.initialize (search-libs.min.js:9)
    at child.Backbone.View (libraries.min.js:1233)
    at new child (libraries.min.js:1893)
    at child.initialize (search-libs.min.js:9)
    at child.Backbone.View (libraries.min.js:1233)
    at new child (libraries.min.js:1893)
    at child.initialize (search-libs.min.js:9)
    at child.Backbone.Router (libraries.min.js:1481)
    at new child (libraries.min.js:1893)
    at HTMLDocument.<anonymous> (search-libs.min.js:9)

This issue only occurs on s3 via tarbell publish staging. Case search page loads OK in local testing i.e. tarbell generate/serve.

**Comment by mattkiefer** [comment]
http://projects.chicagoreporter.com/sandbox17/search/cases/
![image](https://cloud.githubusercontent.com/assets/638427/26689939/266af708-46bd-11e7-93b1-0777d12790f8.png)

**Comment by benlk** [comment]
Which branch is this in?

**Comment by benlk** [comment]
The referenced line in search-libs.min.js is, in the INN/master branch:

```js
return this.$el.chosen({width:"200px",disable_search:!0}
```
That minified file comes from https://github.com/INN/cpd-settlements/blob/master/assets/js/search.js#L621:

```js

  var CaseListSort = Backbone.View.extend({
    initialize: function(options) {
      this.$el.chosen({ width: '200px', disable_search : true});
      this.caseList = options.caseList;
      this.caseList.cases.on(
        'sort', this.caseList.renderFiltered.bind(this.caseList)
      );
      Backbone.View.prototype.initialize.apply(this, arguments);
      return this;
    },

    events: {
      'change': 'sortCaseList'
    },

    sortCaseList: function(event) {
      var option = $(event.currentTarget).val();
      this.caseList.sortElements(option);
    },
  });
```

This error shows up on most pages in the app on http://projects.chicagoreporter.com/sandbox/, not just  the search page.

**Comment by benlk** [comment]
I think it's because we're referencing $el, but it's not defined anywhere in the object. @julia67, do you have any ideas?

**Comment by mattkiefer** [comment]
I'm probably not concerned with this issue unless you're seeing it, too. 

After we publish the updated database, I'll try again and see if it persists.
